### ISSUE TITLE
Consider depending on a later version of PHPUnit

### ISSUE THREAD

**Issue by michaelarnauts** [camunda/camunda-bpm-php-sdk#5]
Currently, camunda-bpm-php-sdk depends on PHPUnit 3.7.21 (forced on this version). When we use camunda-bpm-php-sdk as part of a framework that also depends on PHPUnit, we get an version conflict.

This could be resolved to change the version dependency to a later version (like ~4.0).

**Comment by shentschel** [comment]
Hi @michaelarnauts,

I have no problem with a new version of PHPUnit :) So thanks for contributing to the project! :+1:

**Comment by Stitch7** [comment]
Same Problem here, can not use it in our project due to the old phpunit dependency which conflicts with our newer version.

**Comment by falko** [comment]
Maybe this can help:
https://getcomposer.org/doc/articles/troubleshooting.md#need-to-override-a-package-version

**Comment by michaelarnauts** [comment]
Actually, you don't need PHPUnit in non-dev mode of the package, but the composer.json file insist in doing this. I didn't change this in my earlyer PR. Check out the PR above.
